### ISSUE TITLE
Cannot start service... Missing auth file?

### ISSUE THREAD

**Issue by asprunt** [davesteele/cloudprint-service#3]
Thread transferred from the Google+ page: https://plus.google.com/114224856151152598318/posts

The install seemed to go just fine, as did the login:

pi@raspbmc:/home$ sudo service cloudprintd login
Accounts with 2 factor authentication require an application-specific password
Google username: xxxxxx
Password: 
Added Printer Xerox_Phaser_3300MFP

I can see the printer on the Google cloudprint page, but I cannot see the authfiles

pi@raspbmc:~$ sudo ls -alf /root/
.profile  .bashrc  .pki  .  ..  .pip

Starting the service does not work

pi@raspbmc:/home$ sudo service cloudprintd start
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.10', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 418, in main
    handler = logging.handlers.SysLogHandler(address='/dev/log')
  File "/usr/lib/python2.7/logging/handlers.py", line 758, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 775, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Nor does logging out:

pi@raspbmc:/home$ sudo service cloudprintd logout
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.10', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 418, in main
    handler = logging.handlers.SysLogHandler(address='/dev/log')
  File "/usr/lib/python2.7/logging/handlers.py", line 758, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 775, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Any suggestions? This isn't really my field, so I could be doing something stupid, but I tried to follow the instructions carefully.

Could this be related to how the authfile is being stored? The "~" syntax may not be working quite right in that it doesn't re-direct to the root home directory for sudo...?

pi@raspbmc:~$ ls ~/
file1  file2.py      file3.pub.txt
downloads    file2.py.zip
pi@raspbmc:~$ sudo ls ~/
file1  file2.py      file3.pub.txt
downloads    file2.py.zip

Note that I'm running all this on raspxbmc, not the "normal" installation.

Thanks,
Alex

**Comment by davesteele** [comment]
Recent releases pull in a system logger. Closing.
