### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by tobiasjan** [davesteele/cloudprint-service#52]
Hi davesteele,

tried your project but i only can add the printers to google but they are offline all the time.
When i start the service i get the following message:
Polling for jobs on Printer1
Polling for jobs on Printer2
Establishing connection to xmpp server talk.google.com:5223
ERROR: Could not Connect to Cloud Service. Will Try again in 60 Seconds
Traceback (most recent call last):
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 455, in process_jobs_once
    xmpp_conn.connect(XMPP_SERVER_HOST, XMPP_SERVER_PORT, cpp.auth)
  File "/usr/share/cloudprint/cloudprint/xmpp.py", line 147, in connect
    self._wrappedsock.connect((host, port))
  File "/usr/lib/python2.7/ssl.py", line 876, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python2.7/ssl.py", line 863, in _real_connect
    socket.connect(self, addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

im stuck at this point. Hope for your help

**Comment by davesteele** [comment]
Is TCP port 5223 blocked on your end? It's used to maintain status with the service.

**Comment by tobiasjan** [comment]
Hello dave,
thank you the problem is solved.
